### ISSUE TITLE
启动进程一直都在，导致后面排队的进程无法执行。

### ISSUE THREAD

**Issue by jlzsss** [frainzy1477/luci-app-trojan#1]
打开luci-app-trojan后，一直出现 /bin/sh /etc/rc.common /etc/init.d/trojan boot 导致后面排对的进程无法执行。

**Comment by frainzy1477** [comment]
> 打开luci-app-trojan后，一直出现 /bin/sh /etc/rc.common /etc/init.d/trojan boot 导致后面排对的进程无法执行。

您可以吧屏幕截图或错误日志给我看看

**Comment by jlzsss** [comment]
![进程](https://user-images.githubusercontent.com/2213275/91673762-3c5bd980-eb68-11ea-9342-06da8bfaa213.jpg)
