### ISSUE TITLE
最新版本的百度、淘宝等检查显示不正常！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [frainzy1477/luci-app-trojan#16]
![image](https://user-images.githubusercontent.com/45259624/116806694-5d465580-ab61-11eb-9866-77f37a402ed7.png)

**Comment by frainzy1477** [comment]
试试 这个 https://github.com/frainzy1477/luci-app-trojan/releases/download/v2.0.5/luci-theme-rosy_git-20.040.13689-536cde3-1_all.ipk
可能是你的主题问题

**Comment by zxlhhyccc** [comment]
> 试试 这个 https://github.com/frainzy1477/luci-app-trojan/releases/download/v2.0.5/luci-theme-rosy_git-20.040.13689-536cde3-1_all.ipk
> 可能是你的主题问题

一、确实是主题问题，我是官方master分支的2020主题，能否适配一下这个主题？2.0.2版本在2020主题下正常。。。。
二、文件权限存在问题，比如：init文件的权限是0664而不是0755，usr/share/trojan/*.sh文件的权限全部是0664而不是0755，请修正权限。。。。
三、init文件和*.sh文件和htm文件代码中存在大量的空格字符，这些空格字符有没有影响。。。

**Comment by frainzy1477** [comment]
> > 试试 这个 https://github.com/frainzy1477/luci-app-trojan/releases/download/v2.0.5/luci-theme-rosy_git-20.040.13689-536cde3-1_all.ipk
> > 可能是你的主题问题
> 
> 一、确实是主题问题，我是官方master分支的2020主题，能否适配一下这个主题？2.0.2版本在2020主题下正常。。。。
> 二、文件权限存在问题，比如：init文件的权限是0664而不是0755，usr/share/trojan/_.sh文件的权限全部是0664而不是0755，请修正权限。。。。 三、init文件和_.sh文件和htm文件代码中存在大量的空格字符，这些空格字符有没有影响。。。

更新了
