### ISSUE TITLE
最新版本系统日志中出现找不到json文件，正常吗？

### ISSUE THREAD

**Issue by zxlhhyccc** [frainzy1477/luci-app-trojan#18]
![image](https://user-images.githubusercontent.com/45259624/116818505-440fca00-ab9e-11eb-8148-ab482b4b13ff.png)

**Comment by frainzy1477** [comment]
试试v2.0.6看看

**Comment by zxlhhyccc** [comment]
> 试试v2.0.6看看

**2.0.6版本的网络检测正常了，但系统日志中还是出现大量的找不到json文件情况！是否需要添加一个json的配置模板？**
![image](https://user-images.githubusercontent.com/45259624/116852466-f12e2500-ac26-11eb-94ce-5ab2fa71e7d6.png)

**Comment by frainzy1477** [comment]
你连不上？？

**Comment by zxlhhyccc** [comment]
> 你连不上？？

不是连接不上去问题，是进插件时系统日志出现此种情况！
