### ISSUE TITLE
服务器订阅地址栏多了一个空的输入框！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [frainzy1477/luci-app-trojan#27]
![image](https://user-images.githubusercontent.com/45259624/116963687-22b4f800-acdc-11eb-8a0d-ab5b8978b388.png)

**Comment by frainzy1477** [comment]
很多问题是你的主题问题，rosy主题都没有这问题
![image](https://user-images.githubusercontent.com/49537471/116985060-82e77200-acbb-11eb-8262-b3d581315758.png)

**Comment by zxlhhyccc** [comment]
> 很多问题是你的主题问题，rosy主题都没有这问题
> ![image](https://user-images.githubusercontent.com/49537471/116985060-82e77200-acbb-11eb-8262-b3d581315758.png)

换了几个主题都是此问题，估计是个别主题没问题吧。。。。
![image](https://user-images.githubusercontent.com/45259624/117015812-a8f52c80-ad24-11eb-9f65-c2e906bbb5b0.png)
![image](https://user-images.githubusercontent.com/45259624/117015918-c32f0a80-ad24-11eb-9641-b971d49c3296.png)
![image](https://user-images.githubusercontent.com/45259624/117016002-d7730780-ad24-11eb-9ac6-4ff7a5da6196.png)
