### ISSUE TITLE
我把源码丢进lean/package目录下，编译后报错No rule to make target？

### ISSUE THREAD

**Issue by hilobekerfulaisien** [frainzy1477/luci-app-trojan#4]
我把源码丢进lean/package目录下，编译后报错No rule to make target？
直接下载all.ipk包，上传tmp安装，报错依赖kernel 5.xxx？
设备是netgear r7000，所以来问下这源码是不是只支持x64？

**Comment by hilobekerfulaisien** [comment]
设备是netgear r7000，所以来问下这源码是不是只支持x64？

**Comment by frainzy1477** [comment]
> 我把源码丢进lean/package目录下，编译后报错No rule to make target？
> 直接下载all.ipk包，上传tmp安装，报错依赖kernel 5.xxx？
> 设备是netgear r7000，所以来问下这源码是不是只支持x64？

没有啊
https://github.com/frainzy1477/Actions-Lean-OpenWrt/actions
