### ISSUE TITLE
插件运行后，谷歌和YouTube检测显示不通，但实际已经翻墙！！

### ISSUE THREAD

**Issue by zxlhhyccc** [frainzy1477/luci-app-trojan#42]
**使用其他翻墙插件却检测谷歌、youtube正常！！**
![image](https://user-images.githubusercontent.com/45259624/117480328-09d66c00-af94-11eb-968c-0b0c18c2a688.png)
![image](https://user-images.githubusercontent.com/45259624/117480855-b7e21600-af94-11eb-9169-9ef602b6eb40.png)

**Comment by frainzy1477** [comment]
https://github.com/frainzy1477/luci-app-trojan/actions/runs/820967477
