### ISSUE TITLE
更新到最新版本，谷歌和youtube显示无法访问，但youtube等均正常登录！

### ISSUE THREAD

**Issue by zxlhhyccc** [frainzy1477/luci-app-trojan#44]
![image](https://user-images.githubusercontent.com/45259624/117532726-86f8f400-b01b-11eb-8d43-6091b4980369.png)

dalao，谷歌、油管显示无法访问是什么原因？能想办法解决吗？另外一个就是，trojan-go正常翻墙了，其他插件比如：ssrplue、passwall、baypass均显示检测失败，请问dalao这又是什么问题导致的？

**Comment by bao3** [comment]
我也有同样的情况。我的 openwrt 是纯净的，没有任何其他工具安装，安装了本插件后，和题主情况一样。实际上却是能翻墙的。
