### ISSUE TITLE
能否添加使用本机端口作为dns服务的dns解析功能？

### ISSUE THREAD

**Issue by zxlhhyccc** [frainzy1477/luci-app-trojan#46]
如果加了使用本机端口解析dns功能，可以兼容使用其他dns解析插件，比如：smartdns、ADG

**Comment by frainzy1477** [comment]
> 如果加了使用本机端口解析dns功能，可以兼容使用其他dns解析插件，比如：smartdns、ADG

禁用luci-apo-trojan插件dns,可以用其他dns解析插件

**Comment by zxlhhyccc** [comment]
> > 如果加了使用本机端口解析dns功能，可以兼容使用其他dns解析插件，比如：smartdns、ADG
> 
> 禁用luci-apo-trojan插件dns,可以用其他dns解析插件

禁用插件自身dns解析并启用smartdns后，无法上油管，源码中pdnsd的dns服务端口貌似是5335，我把smartdns的第二服务器已设置为5335端口，是否smartdns需设置其他的端口？如smartdns需设置其他端口，请问端口是什么？
![image](https://user-images.githubusercontent.com/45259624/117824011-abb1cd80-b2a0-11eb-9525-06526a079b9e.png)

**Comment by frainzy1477** [comment]
> > > 如果加了使用本机端口解析dns功能，可以兼容使用其他dns解析插件，比如：smartdns、ADG
> > 
> > 
> > 禁用luci-apo-trojan插件dns,可以用其他dns解析插件
> 
> 禁用插件自身dns解析并启用smartdns后，无法上油管，源码中pdnsd的dns服务端口貌似是5335，我把smartdns的第二服务器已设置为5335端口，是否smartdns需设置其他的端口？如smartdns需设置其他端口，请问端口是什么？
> ![image](https://user-images.githubusercontent.com/45259624/117824011-abb1cd80-b2a0-11eb-9525-06526a079b9e.png)

禁用luci-apo-trojan插件dns,pdnsd端口5335也禁用,smartdns解析ip问题,不是端口问题.

**Comment by frainzy1477** [comment]
![image](https://user-images.githubusercontent.com/49537471/117827794-d2501400-b260-11eb-8122-e7758c306330.png)


设置自定义DNS 服务器

**Comment by zxlhhyccc** [comment]
> ![image](https://user-images.githubusercontent.com/49537471/117827794-d2501400-b260-11eb-8122-e7758c306330.png)
> 
> 设置自定义DNS 服务器

按照dalao你的说法，禁用pdnsd解析后，只能是使用自定义dns，无法使用其他插件进行解析对么？另外自定义dns服务器应该设置在wan口还是lan口？看你的截图设置在lan口！
