### ISSUE TITLE
2.1.1版使用ws模式报错

### ISSUE THREAD

**Issue by jlzsss** [frainzy1477/luci-app-trojan#47]
2.1.1版使用ws模式报错，报错内容如下：

[ERROR] 2021/05/12 14:57:33 github.com/frainzy1477/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message

**Comment by zxlhhyccc** [comment]
> 2.1.1版使用ws模式报错，报错内容如下：
> 
> [ERROR] 2021/05/12 14:57:33 github.com/frainzy1477/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message

ws模式没问题，你服务器可能参数不对。。。

**Comment by frainzy1477** [comment]
> 2.1.1版使用ws模式报错，报错内容如下：
> 
> [ERROR] 2021/05/12 14:57:33 github.com/frainzy1477/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message

你服务器问题

**Comment by jlzsss** [comment]
知道了，谢谢。
