### ISSUE TITLE
Missing pdnsd-alt dependency for Linksys router

### ISSUE THREAD

**Issue by mgz77** [frainzy1477/luci-app-trojan#5]
Tried to install in OpenWrt 19.07.4, complains about missing dependency of pdnsd-alt.

I have a Linksys wrt32x router with cpu model arm_cortex-a9_vfpv3-d16. I can't find an ipk for pdnsd-alt for my cpu model. Any suggestions? Thank you.

**Comment by frainzy1477** [comment]
you can manually search online ,download and install or use this https://github.com/frainzy1477/luci-app-trojan/releases/download/v2.0.2/luci-app-trojan_v2.0.2_all_no_pdnsd_dep.ipk
