### ISSUE TITLE
在更新页面遇到问题

### ISSUE THREAD

**Issue by LuuHu** [frainzy1477/luci-app-trojan#7]
![image](https://user-images.githubusercontent.com/41143797/101776564-14e3b800-3b2c-11eb-91e6-fbc2c139e2ba.png)

- OpenWrt:19.07.5
- luci-app-trojan:2.0.2

当我选择架构为linux-armv8后点击下载，从log看出下载成了amd64架构的包。

设备：树莓派3b+

**Comment by frainzy1477** [comment]
> ![image](https://user-images.githubusercontent.com/41143797/101776564-14e3b800-3b2c-11eb-91e6-fbc2c139e2ba.png)
> 
> * OpenWrt:19.07.5
> * luci-app-trojan:2.0.2
> 
> 当我选择架构为linux-armv8后点击下载，从log看出下载成了amd64架构的包。
> 
> 设备：树莓派3b+

Your router may not have enough free space.

**Comment by LuuHu** [comment]
Memory seems doesn't result the problem, the device remains a few GB storages. Is there any method or steps of install trojan-core manually?
Thanks a lot.

**Comment by frainzy1477** [comment]
> Memory seems doesn't result the problem, the device remains a few GB storages. Is there any method or steps of install trojan-core manually?
> Thanks a lot.

can update to v2.0.3
