### ISSUE TITLE
Not support arm_cortex-a9?

### ISSUE THREAD

**Issue by yukeiyang** [frainzy1477/luci-app-trojan#8]
When install this ipk, display this issue:

* satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-trojan:
 *      pdnsd-alt

**Comment by yukeiyang** [comment]
In other words, How can I know my device supported or not by this client?

When install this ipk, need pdnsd-alt, but https://github.com/mengskysama/openwrt-pdnsd/releases  only supports very few device, such as bcm53xx, brcm47xx, rampis-24kec, atheros. 

How about others? They all can not install luci-app-trojan too?

**Comment by yukeiyang** [comment]
So, If i not use pdnsd, it will works well? 

If so, I can manually install this https://github.com/frainzy1477/luci-app-trojan/releases/download/v2.0.2/luci-app-trojan_v2.0.2_all_no_pdnsd_dep.ipk, right?

**Comment by frainzy1477** [comment]
> So, If i not use pdnsd, it will works well?
> 
> If so, I can manually install this https://github.com/frainzy1477/luci-app-trojan/releases/download/v2.0.2/luci-app-trojan_v2.0.2_all_no_pdnsd_dep.ipk, right?

works, you can use dnscrypt instead of pdnsd

**Comment by frainzy1477** [comment]
> In other words, How can I know my device supported or not by this client?
> 
> When install this ipk, need pdnsd-alt, but https://github.com/mengskysama/openwrt-pdnsd/releases only supports very few device, such as bcm53xx, brcm47xx, rampis-24kec, atheros.
> 
> How about others? They all can not install luci-app-trojan too?

yes

**Comment by yukeiyang** [comment]
Thank you.
